define(['angularAMD'],(angularAMD)->
    angularAMD.factory('Fields',->
        {
            fPromise:[
                name:'name'
                text:'标识'
                type:'string'
                show:true
                link:false
                sort:true
                required:true
                default:'des_'
            ,
                name:'url'
                text:'地址'
                type:'string'
                show:true
                link:false
                sort:true
                required:true
                default:''
            ,
                name:'text'
                text:'文本'
                type:'string'
                show:true
                link:false
                sort:false
                required:true
                default:''
            ,
                name:'show'
                text:'显示'
                type:'string'
                show:true
                link:false
                required:true
                default:true
                render:(data,full)->
                    if data is true
                        return '是'
                    else
                        return '否'
            ,
                name:'icon'
                text:'图标'
                type:'icon'
                show:true
                link:false
                sort:false
                required:true
                default:true
            ,
                name:'wide'
                text:'全屏展示'
                type:'boolean'
                show:true
                link:false
                sort:true
                required:true
                default:true
                render:(data,full)->
                    if data is true
                        return '<div class="btn-icon btn-icon-round btn-icon-xs btn-success"><i class="fa fa-check"></i></div>'
                    else
                        return '<div class="btn-icon btn-icon-round btn-icon-xs btn-danger"><i class="fa fa-times"></i></div>'
            ,
                name:'$edit'
                text:'操作'
                type:'edit'
                show:true
                link:false
                sort:false
                style:'width:100px;'
            ]
            fCat:[
                name:'title'
                text:'名称'
                type:'string'
                show:true
                sort:true
                required:true
                search:'默认'
                pattern:''
                lineEdit:true
                edit:true
                extra:'average'#total:求总和/average:求平均
                extra_render:(data,full)->
                    data + '/' + _.where(full,{name:'label'})[0].$extra
            ,
                name:'label'
                text:'上级分类'
                type:'select'
                select:{key:'id',value:'title',model:'fLabel'}
                show:true
                sort:true
                required:true
                edit:true
                extra:'total'
            ,
                name:'multi'
                text:'多选择'
                type:'multiple'
                select:{key:'id',value:'title',model:'fLabel'}
                show:true
                sort:true
                required:true
                edit:true
            ,
                name:'multi_refresh'
                text:'动态多选择'
                type:'multiple_refresh'
                select:{key:'id',value:'title',model:'fLabel',limit:8}
                show:true
                sort:true
                required:true
                edit:true
            ,
                name:'$edit'
                text:'操作'
                type:'edit'
                show:true
                link:false
                sort:false
                style:'width:100px;'
            ]
        }

    )
)
