###
#define(['angularAMD'], (angularAMD)->
#    angularAMD
#    .service('sMenu',
#        (fMenu)->
#            fMenu
#    )
#    .service('sSiteTypeRule',
#        (fSiteTypeRule)->
#            fSiteTypeRule
#    )
#    .service('sWebSiteType',
#        (fWebSiteType)->
#            fWebSiteType
#    )
#    .service('sImageFormationRule',
#        (fImageFormationRule)->
#            fImageFormationRule
#    )
#    .service('sWebSiteMain',
#        (fWebSiteMain)->
#            fWebSiteMain
#    )
#    .service('sWebSiteDomain',
#        (fWebSiteDomain)->
#            fWebSiteDomain
#    )
#    .service('sSubWebSiteDomain',
#        (fSubWebSiteDomain)->
#            fSubWebSiteDomain
#    )
#    .service('sWebClassifyReport',
#        (fWebClassifyReport)->
#            fWebClassifyReport
#    )
#    .service('sWebClassifyReportSub',
#        (fWebClassifyReportSub)->
#            fWebClassifyReportSub
#    )
#    .service('sFlowAnalysisConfig',
#        (fFlowAnalysisConfig)->
#            fFlowAnalysisConfig
#    )
#    .service('sLongReportConfig',
#        (fLongReportConfig)->
#            fLongReportConfig
#    )
#    .service('sTaskList',
#        (fTaskList)->
#            fTaskList
#    )
#    .service('sTaskQueue',
#        (fTaskQueue)->
#            fTaskQueue
#    )
#    .service('sTaskTemplate',
#        (fTaskTemplate)->
#            fTaskTemplate
#    )
#    .service('sUsersList',
#        (fUsersList)->
#            fUsersList
#    )
#    .service('sRoleMange',
#        (fRoleMange)->
#            fRoleMange
#    )
#    .service('sDomainBatchAnalysis',
#        (fDomainBatchAnalysis)->
#            fDomainBatchAnalysis
#    )
#    .service('sDomainBatchAnalysis_Detail',
#        (fDomainBatchAnalysis_Detail)->
#            fDomainBatchAnalysis_Detail
#    )
#    .service('sLogInfo',
#        (fLogInfo)->
#            fLogInfo
#    )
#)
###
